planet:
  name: 'Earth-Sun-Moderate'
  Rp: 6.3781e8
  gs: 980.0
  orbit_radius: 1.0
  sl_angle: 58.0
  f_diurnal: 0.5
  rocky: True
atmosphere:
  atm_type: 'file'
  atm_file: 'atm/atm_Earth_Jan_Kzz.txt'
  P_b: 1.0e6
  P_t: 5.0e-2
  nz: 120
  Kzz_prof: 'file'
  const_mix:
    N2: 0.79
    O2: 0.20
    H2O: 1.0e-6
    CO2: 0.0004
    SO2: 2.0e-10
star:
  type: 'Sun'
  r_star: 1.0
  sflux_file: 'atm/stellar_flux/Gueymard_solar.txt'
chemistry:
  network: 'thermo/SNCHO_full_photo_network.txt'
  use_photo: True
  use_botflux: True
  bot_BC_flux_file: 'boundary_conditions/bc_earth_exofarm_moderate_full.txt'
  out_name: 'Earth_A2_Moderate.vul'
