planet:
  name: 'Earth-Trappist-Extreme'
  Rp: 6.3781e8
  gs: 980.0
  orbit_radius: 0.02928
  sl_angle: 48.0
  f_diurnal: 1.0
  rocky: True
atmosphere:
  atm_type: 'file'
  atm_file: 'atm/atm_Earth_Jan_Kzz.txt'
  P_b: 1.0e6
  P_t: 5.0e-2
  nz: 120
  Kzz_prof: 'file'
  const_mix:
    N2: 0.79
    O2: 0.20
    H2O: 1.0e-6
    CO2: 0.0004
star:
  type: 'TRAPPIST-1'
  r_star: 0.117
  sflux_file: 'atm/stellar_flux/TRAPPIST1_surface.txt'
chemistry:
  network: 'thermo/NCHO_earth_photo_network.txt'
  use_photo: True
  use_botflux: True
  bot_BC_flux_file: 'boundary_conditions/bc_earth_exofarm_full.txt'
  out_name: 'Trappist_A3_Extreme.vul'